In [ ]:
# GETTING FILS

from google.colab import files

uploaded = files.upload()

Saving Wine_data.xlsx to Wine_data.xlsx


In [ ]:
# TASK 3
import pandas as panda
import numpy as np

data = panda.read_csv('Share_data.csv')

data = data.to_numpy()
data

# MEAN
print(data)
opene = data[:,1:2]
print(opene.mean())
closee = data[:,2:]
print(closee.mean())


#MODE
from scipy import stats

a = stats.mode(opene)
b = stats.mode(closee)
print(a)
print(b)

#MEDIAN

print(np.median(opene))
print(np.median(closee))

# STD
print(np.std(opene))
print(np.std(closee))

# RMSE (GOOD LUCK REMEMEBRING IT)
print(np.sqrt(np.mean((opene-closee)**2)))

[[ 1 10 12]
 [ 2 13 15]
 [ 3 11 14]
 [ 4 13 11]
 [ 5 10  9]
 [ 6 11 12]
 [ 7 11 13]
 [ 8 12 11]
 [ 9 10 14]
 [10 13 15]
 [11 15 17]
 [12 16 15]
 [13 15 14]
 [14 15 16]
 [15 16 18]
 [16 17 18]
 [17 17 19]
 [18 19 17]
 [19 17 17]
 [20 18 20]]
13.95
14.85
ModeResult(mode=array([[10]]), count=array([[3]]))
ModeResult(mode=array([[14]]), count=array([[3]]))
14.0
15.0
2.8368115905008566
2.8683619018526936
1.8973665961010275


<ipython-input-51-56f043e59ede>:21: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  a = stats.mode(opene)
<ipython-input-51-56f043e59ede>:22: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  b = stats.mode(closee)


In [ ]:
# TASK 1

data = panda.read_csv('Tumor_data.csv')
print(data.columns)
data = data.to_numpy()

dt1 = data[:,0:1]
dt2 = data[:,1:2]
dt3 = data[:,2:3]
dt4 = data[:,3:4]
dt5 = data[:,4:]

print(dt1.mean())
print(dt2.mean())
print(dt3.mean())
print(dt4.mean())
print(dt5.mean())

# Task 1 -> 2

print(data[0])
for i in range(data.shape[0]):
  if data[i][0] > dt1.mean():
    print(data[i])




Index(['radius', 'texture', 'perimeter', 'area', 'smoothness'], dtype='object')
14.127291739894552
19.289648506151142
91.96903339191564
654.8891036906855
0.0963602811950791
[1.799e+01 1.038e+01 1.228e+02 1.001e+03 1.184e-01]
[1.799e+01 1.038e+01 1.228e+02 1.001e+03 1.184e-01]
[2.057e+01 1.777e+01 1.329e+02 1.326e+03 8.474e-02]
[1.969e+01 2.125e+01 1.300e+02 1.203e+03 1.096e-01]
[2.029e+01 1.434e+01 1.351e+02 1.297e+03 1.003e-01]
[1.825e+01 1.998e+01 1.196e+02 1.040e+03 9.463e-02]
[1.602e+01 2.324e+01 1.027e+02 7.978e+02 8.206e-02]
[1.578e+01 1.789e+01 1.036e+02 7.810e+02 9.710e-02]
[1.917e+01 2.480e+01 1.324e+02 1.123e+03 9.740e-02]
[1.585e+01 2.395e+01 1.037e+02 7.827e+02 8.401e-02]
[1.454e+01 2.754e+01 9.673e+01 6.588e+02 1.139e-01]
[1.468e+01 2.013e+01 9.474e+01 6.845e+02 9.867e-02]
[1.613e+01 2.068e+01 1.081e+02 7.988e+02 1.170e-01]
[1.981e+01 2.215e+01 1.300e+02 1.260e+03 9.831e-02]
[1.534e+01 1.426e+01 1.025e+02 7.044e+02 1.073e-01]
[2.116e+01 2.304e+01 1.372e+02 1.404e+03 9.428e

In [ ]:
# TASK 1 - B

data = panda.read_excel('Wine_data.xlsx')
#print(data.columns)
data = data.to_numpy()

# b1
for i in range(data.shape[0]):
  if data[i][0] > data[i][4]:
    print(data[i])

# b2
#print(data[0])
hue_data = data[:,10:11]
#print(hue_data.min())
#print(hue_data.max())

#b3
alcohol_data = data[:,0:1]
color_data = data[:,9:10]
cor = np.corrcoef(alcohol_data, color_data)

for i in range(data.shape[0]):
  if i%2 != 0 :
    print(data[i])

[1.32e+01 1.78e+00 2.14e+00 1.12e+01 1.00e+02 2.65e+00 2.76e+00 2.60e-01
 1.28e+00 4.38e+00 1.05e+00 3.40e+00 1.05e+03]
[1.437e+01 1.950e+00 2.500e+00 1.680e+01 1.130e+02 3.850e+00 3.490e+00
 2.400e-01 2.180e+00 7.800e+00 8.600e-01 3.450e+00 1.480e+03]
[1.42e+01 1.76e+00 2.45e+00 1.52e+01 1.12e+02 3.27e+00 3.39e+00 3.40e-01
 1.97e+00 6.75e+00 1.05e+00 2.85e+00 1.45e+03]
[1.406e+01 2.150e+00 2.610e+00 1.760e+01 1.210e+02 2.600e+00 2.510e+00
 3.100e-01 1.250e+00 5.050e+00 1.060e+00 3.580e+00 1.295e+03]
[1.386e+01 1.350e+00 2.270e+00 1.600e+01 9.800e+01 2.980e+00 3.150e+00
 2.200e-01 1.850e+00 7.220e+00 1.010e+00 3.550e+00 1.045e+03]
[1.412e+01 1.480e+00 2.320e+00 1.680e+01 9.500e+01 2.200e+00 2.430e+00
 2.600e-01 1.570e+00 5.000e+00 1.170e+00 2.820e+00 1.280e+03]
[1.475e+01 1.730e+00 2.390e+00 1.140e+01 9.100e+01 3.100e+00 3.690e+00
 4.300e-01 2.810e+00 5.400e+00 1.250e+00 2.730e+00 1.150e+03]
[1.363e+01 1.810e+00 2.700e+00 1.720e+01 1.120e+02 2.850e+00 2.910e+00
 3.000e-01 1.460e+00 7.3

/usr/local/lib/python3.9/dist-packages/numpy/lib/function_base.py:2821: RuntimeWarning: Degrees of freedom <= 0 for slice
  c = cov(x, y, rowvar, dtype=dtype)
/usr/local/lib/python3.9/dist-packages/numpy/lib/function_base.py:2680: RuntimeWarning: divide by zero encountered in true_divide
  c *= np.true_divide(1, fact)
/usr/local/lib/python3.9/dist-packages/numpy/lib/function_base.py:2680: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)
