In [ ]:
import numpy as np
#filein = "Tumor_data"
data = np.loadtxt(open("Tumor_data.csv", "rb"), delimiter=",", skiprows= 1) # "loadtxt" function returns n D array from the file data. 
#data = np.loadtxt(open("Tumor_data.csv", "rb"), delimiter=",", dtype = np.str, skiprows=1)
data.shape

(569, 5)

# Reading data from the colab default folder with loadtxt() function

In [ ]:
import numpy as np
data = np.loadtxt("Tumor_data.csv", delimiter=",", skiprows=1) # "skiprows = 1" removes the first row, if skiprows is more than 1 then it removes number of rows, startiing from the first till specified value. "skiprows = 0" will include all the rows.
print(data)


[[1.799e+01 1.038e+01 1.228e+02 1.001e+03 1.184e-01]
 [2.057e+01 1.777e+01 1.329e+02 1.326e+03 8.474e-02]
 [1.969e+01 2.125e+01 1.300e+02 1.203e+03 1.096e-01]
 ...
 [1.660e+01 2.808e+01 1.083e+02 8.581e+02 8.455e-02]
 [2.060e+01 2.933e+01 1.401e+02 1.265e+03 1.178e-01]
 [7.760e+00 2.454e+01 4.792e+01 1.810e+02 5.263e-02]]


In [ ]:
import numpy as np
data = np.loadtxt("Student_Data.tsv", delimiter="\t", skiprows=1, usecols = (1,2,3)) # "usecols = (1,2,3)" selects specified columns from the table 
print(data)
print(type(data))
data.dtype      # default type is float


[[12. 19. 14.]
 [14. 15. 18.]
 [11. 14. 16.]
 [17. 13. 19.]
 [19. 12. 15.]
 [15. 11. 17.]
 [17. 14. 16.]
 [10. 11. 13.]]
<class 'numpy.ndarray'>


dtype('float64')

In [ ]:
# changing the type of data as per our requirement
import numpy as np
data1 = np.loadtxt("Student_Data.tsv", delimiter="\t",  usecols = (1,2,3), dtype = int , skiprows=2,)  # we can specify the width of data type with "int8, int16 an so on",
print(data1)
data1.dtype

[[14 15 18]
 [11 14 16]
 [17 13 19]
 [19 12 15]
 [15 11 17]
 [17 14 16]
 [10 11 13]]


dtype('int64')

In [ ]:
data.shape

(8, 3)

In [ ]:
print(type(data))

In [ ]:
data.shape

(569, 5)

In [ ]:
data2 = np.loadtxt("Student_Data.tsv", delimiter="\t", dtype = np.str, skiprows=0)  # we can specify datatype as string to consider entire dataset
print(data2)

[['Rollno' 'DAP' 'PS' 'WT']
 ['A1' '12' '19' '14']
 ['A2' '14' '15' '18']
 ['A3' '11' '14' '16']
 ['A4' '17' '13' '19']
 ['A5' '19' '12' '15']
 ['A6' '15' '11' '17']
 ['A7' '17' '14' '16']
 ['A8' '10' '11' '13']]


<ipython-input-60-76921bdb0af8>:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  data2 = np.loadtxt("Student_Data.tsv", delimiter="\t", dtype = np.str, skiprows=0)  # we can specify datatype as string to consider entire dataset


In [ ]:
print(data2[:,1:])

[['DAP' 'PS' 'WT']
 ['12' '19' '14']
 ['14' '15' '18']
 ['11' '14' '16']
 ['17' '13' '19']
 ['19' '12' '15']
 ['15' '11' '17']
 ['17' '14' '16']
 ['10' '11' '13']]


In [ ]:
print(data2[:,2:])

In [ ]:
print(data2[1:,1:])

In [ ]:
data3 = np.loadtxt("Student_Data.tsv", delimiter="\t", dtype = np.str_,  usecols = (0))  # we can specify datatype as string to consider entire dataset
print(data3)

['Rollno' 'A1' 'A2' 'A3' 'A4' 'A5' 'A6' 'A7' 'A8']


In [ ]:
data4 = np.loadtxt("Tumor_data.csv", delimiter=",", skiprows= 1)
print(data4)

In [ ]:
data4.shape
data4.dtype

dtype('float64')

# Generate from text file function - genfromtxt() , basically used when there are some missing values presesnt in data set.

In [ ]:
import numpy as np
data = np.genfromtxt("Student_Data.csv")
data

array([nan, nan, nan, nan, nan, nan, nan, nan])

In [ ]:
import numpy as np
data = np.genfromtxt("Student_Data.csv", invalid_raise=False)
data

array([nan, nan, nan, nan, nan, nan, nan, nan])

In [ ]:
import numpy as np
data = np.genfromtxt("Student_Data.csv", delimiter = ",")
data

array([[nan, nan, nan, nan],
       [nan, 12., 19., 14.],
       [nan, 14., 15., 18.],
       [nan, 11., 14., 16.],
       [nan, 17., 13., 19.],
       [nan, nan, 20., 12.],
       [nan, 12., nan, nan],
       [nan, 15., 13., nan]])

In [ ]:
import numpy as np
data = np.genfromtxt("Student_Data.csv", delimiter = ",", filling_values= 0)
data

array([[ 0.,  0.,  0.,  0.],
       [ 0., 12., 19., 14.],
       [ 0., 14., 15., 18.],
       [ 0., 11., 14., 16.],
       [ 0., 17., 13., 19.],
       [ 0.,  0., 20., 12.],
       [ 0., 12.,  0.,  0.],
       [ 0., 15., 13.,  0.]])