In [ ]:
l = [2,3,4,"A"]
l
print(type(l[3])


<class 'str'>


In [ ]:
import numpy as np
a = np.array([2,3,'A'])
print(a)
print(type(a[0]))
print(a.dtype)

['2' '3' 'A']
<class 'numpy.str_'>
<U21


In [ ]:
b = np.array([2,3,3])
print(b)
print(type(b[0]))

[2 3 3]
<class 'numpy.int64'>


In [ ]:
# setting data type of the numpy array

m = np.array([2,30,4], dtype = 'int8')
m

array([ 2, 30,  4], dtype=int8)

In [ ]:
m = np.array([20000000,3000000,46000000], dtype = 'int8')
m

array([   0,  -64, -128], dtype=int8)

In [ ]:
l1 = [1,2]
l2 = [2,3]
print(l1*l2)

In [ ]:
b = np.array([2,3,3])
a = np.array([2,3,3])
print(a*b)

[4 9 9]


In [ ]:
a = np.array([[2,3,3],[3,2,2]])
a.dtype  # print type of the array

dtype('int64')

In [ ]:
a.shape # print shape of the array

(3,)

In [ ]:
a.ndim   # get dimension pf teh array

1

In [ ]:
#a.itemsize  # get size of the each element in bytes
b.itemsize

8

In [ ]:
b.nbytes # total size of an array in bytes

24

In [ ]:
import numpy as np
m = np.array([2,30,4], dtype = 'int8')
m

array([ 2, 30,  4], dtype=int8)

In [ ]:
m.itemsize  get size of the each element in bytes

1

In [ ]:
import random
import timeit
n= 100

x = [random.random() for i in range(n)]
print(x)
len(x)


[0.6617205016640735, 0.21549726302474026, 0.800206421726114, 0.28524634012552297, 0.4925043615374348, 0.9488105121174646, 0.2520654137839019, 0.20788680975791396, 0.8644019929489505, 0.7885992824944994, 0.38102922016427043, 0.20574926512479774, 0.38190568117352, 0.6003575294789292, 0.7971922517690103, 0.7704492150783576, 0.03649308096871884, 0.19607305837589606, 0.5871264334848169, 0.29959267323214245, 0.5041160131513095, 0.2911478190634348, 0.8019398028326065, 0.4384067876387133, 0.470180140870078, 0.8160510354169342, 0.9746512470252006, 0.06527960869148641, 0.38711710941724564, 0.06145055361522278, 0.1596963747697544, 0.7989661584130913, 0.6573106619772282, 0.9983456258533534, 0.6402311966226784, 0.0780830108608539, 0.8257117930538337, 0.011154091411269662, 0.11894581068951515, 0.31849321974540723, 0.813627092437801, 0.373181973926053, 0.5082471037714101, 0.1355092110429793, 0.37283617150833603, 0.8557768709048291, 0.6084535922741539, 0.998507369433321, 0.06985866685444608, 0.2179645

100

In [ ]:
y = [random.random() for i in range(n)]

z = [x[i] + y[i] for i in range(n)]
z

In [ ]:
# speed without numpy

%timeit [x[i] + y[i] for i in range(n)]

9.92 µs ± 126 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
xa = np.array(x)
ya = np.array(y)
za = xa + ya
za

In [ ]:
# spped with numpy array
%timeit xa + ya

730 ns ± 263 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [ ]:
# creating 3 D array 
a = np.array([[[2,3]],[[2,2]]])
print(a)
a.shape

[[[2 3]]

 [[2 2]]]


(2, 1, 2)

In [ ]:
a = np.ones((2,2,2))
a

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [ ]:
# Reshaping of an array
a = np.array([[2,3,3],[3,2,2]])
a  # print type of the array
a.reshape(3,2)  # It will not reshape the original array
a

array([[2, 3, 3],
       [3, 2, 2]])

In [ ]:
a = a.reshape(3,2)  # It will reshape the original array
a

array([[2, 3],
       [3, 3],
       [2, 2]])

In [ ]:
# copying array
a = np.array([[[2,3,3],[3,2,2],[1,1,1]], [[2,3,3],[3,2,2],[2,2,2]], [[2,3,3],[3,2,2],[3,3,3]]])
b= a.copy()
print(b)
b.shape


[[[2 3 3]
  [3 2 2]
  [1 1 1]]

 [[2 3 3]
  [3 2 2]
  [2 2 2]]

 [[2 3 3]
  [3 2 2]
  [3 3 3]]]


(3, 3, 3)

In [ ]:
b[0] = 100
b

array([[[100, 100, 100],
        [100, 100, 100],
        [100, 100, 100]],

       [[  2,   3,   3],
        [  3,   2,   2],
        [  2,   2,   2]],

       [[  2,   3,   3],
        [  3,   2,   2],
        [  3,   3,   3]]])

In [ ]:
a

array([[[2, 3, 3],
        [3, 2, 2],
        [1, 1, 1]],

       [[2, 3, 3],
        [3, 2, 2],
        [2, 2, 2]],

       [[2, 3, 3],
        [3, 2, 2],
        [3, 3, 3]]])

# Mathematics

In [ ]:
a = np.array([2,3,3])
a+2
print(a)

[2 3 3]


In [ ]:
a-2

array([0, 1, 1])

#Accessing / changing specific value from the array

In [ ]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [ ]:
a.shape

In [ ]:
# get specific element
a[1,4]

12

In [ ]:
# get specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
# get specific column
a[:,4]

array([ 5, 12])

In [ ]:
# Replacing an element with different value
a[1,4] = 30 
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 30, 13, 14]])

In [ ]:
 # Replacing coulum with different value
 a[:,6] = 100
 a

array([[  1,   2,   3,   4,   5,   6, 100],
       [  8,   9,  10,  11,  30,  13, 100]])

In [ ]:
# Replacing row with different value
a[0,:] = 100
a

array([[100, 100, 100, 100, 100, 100, 100],
       [  8,   9,  10,  11,  30,  13, 100]])

# some matrix manipulation functions 

In [ ]:
# creating an array with intial values with full()
a = np.full((3,3), 30)
a
#a.dtype

dtype('int64')

In [ ]:
# creating an array with intial values with full()
a = np.full((3,3), 30.0)
a
#a.dtype

array([[30., 30., 30.],
       [30., 30., 30.],
       [30., 30., 30.]])

In [ ]:
# creating an array with intial values with full()
np.full((3,3), 30, dtype = 'float32')

array([[30., 30., 30.],
       [30., 30., 30.],
       [30., 30., 30.]], dtype=float32)

In [ ]:
# Repeating an array in a row 
arr = np.array([1,2,3])
a1 = np.repeat(arr, 3, axis =0)
a1

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [ ]:
# Repeating an array row wise
arr = np.array([[1,2,3]])
a1 = np.repeat(arr, 4, axis =0)
a1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [ ]:
# create identity matrix
a= np.identity(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# statistics

In [ ]:
# statistics
a = np.array([[20,10,3],[6,12,8],[12,23,14]])
a
#a.min()
#a.max()

array([[20, 10,  3],
       [ 6, 12,  8],
       [12, 23, 14]])

In [ ]:
a.max(axis = 0)  # column (row selection)

array([20, 23, 14])

In [ ]:
a.max(axis = 1)

array([20, 12, 23])

# Reshaping of an array with reshape()

In [ ]:
# reating array
a = np.array([[20,10,3],[6,12,8]])
a.shape

(2, 3)

In [ ]:
a.reshape(3,2)  # it will not change the original array
#a

array([[20, 10,  3],
       [ 6, 12,  8]])

In [ ]:
# it will change original array
a= a.reshape(3,2)
a

# matrix operations on array

In [ ]:
# mathematical operations on array
a = np.array([[3,3],[3,3]])
b = np.array([[2,2],[2,2]])
print(a)
print(b)
c=a+b
c=a-b
c=a*b
c=a/b
c

In [ ]:
# matrix multiplication
x = np.matmul(a,b)
x

In [ ]:
a = np.array([[3,3],[3,3]])
b = np.array([[2,2],[2,2],[1,1]]) 
print(a)
print(b)
x = np.matmul(a,b) # generate error if matrix size is not as per rule

In [ ]:
# find the determinant
a = np.array([[3,3],[3,3]])
a
np.linalg.det(a)

0.0

In [ ]:
# getting row wise and column wise sum 
a = np.array([[20,10,3],[6,12,8]])
a

array([[20, 10,  3],
       [ 6, 12,  8]])

In [ ]:
np.sum(a, axis = 0) # sum of values of 

array([26, 22, 11])

In [ ]:
np.sum(a,axis = 1)

array([33, 26])

In [ ]:
np.max(a,axis = 0)

array([20, 12,  8])

In [ ]:
np.max(a,axis = 1)

# stacking vectors - Creating multidimensional array from 1 - D

In [ ]:
# vertically stacking vectors
a = np.array([3,3,3])
print(a)
np.vstack([a,a,a])

[3 3 3]


array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [ ]:
# vertically stacking vectors
a = np.array([3,3,3])
b = np.array([4,5,5])
x = np.vstack([a,b])
x.shape

(2, 3)

In [ ]:
# horizonatal stacking vectors

In [ ]:
a = np.array([3,3,3])
b = np.array([4,5,5])
x = np.hstack([a,b])
x

array([3, 3, 3, 4, 5, 5])

In [ ]:
# handling not a number by numpy
np.isnan(np.nan)
#np.isnan(10)
#a = np.isnan([np.log(-1.),1.,np.log(0)])
#a

True