In [ ]:
from PIL import Image
image = Image.open('Image.png')
 
# summarize some details about the image
print(image.format)
print(image.size)
print(image)

PNG
(331, 309)
<PIL.PngImagePlugin.PngImageFile image mode=P size=331x309 at 0x7F786F408880>


In [ ]:
from numpy import asarray
# asarray() class is used to convert

img_data = asarray(image)
 
# <class 'numpy.ndarray'>
print(type(img_data))
 
#  shape
print(img_data.shape)
print(img_data)

<class 'numpy.ndarray'>
(309, 331)
[[ 62  62  46 ...  17  17  17]
 [ 59  62  62 ...  17  17  17]
 [ 59  59  59 ...  17  17  17]
 ...
 [204 204 204 ... 197 197 197]
 [204 197 204 ... 204 204 204]
 [204 204 197 ... 197 204 204]]
